# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1173, 770)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 1001, 641))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.line = QFrame(self.tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 300, 661, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(30, 10, 641, 281))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_2 = QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(260, 10, 311, 251))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_3 = QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)

        self.label_2 = QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)

        self.label = QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)


        self.verticalLayout_3.addLayout(self.gridLayout)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_4 = QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout.addWidget(self.label_4)

        self.label_value_azamith = QLabel(self.verticalLayoutWidget_2)
        self.label_value_azamith.setObjectName(u"label_value_azamith")

        self.horizontalLayout.addWidget(self.label_value_azamith)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_5 = QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_2.addWidget(self.label_5)

        self.final_bearing_label = QLabel(self.verticalLayoutWidget_2)
        self.final_bearing_label.setObjectName(u"final_bearing_label")

        self.horizontalLayout_2.addWidget(self.final_bearing_label)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.midpoint_label = QLabel(self.verticalLayoutWidget_2)
        self.midpoint_label.setObjectName(u"midpoint_label")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midpoint_label.sizePolicy().hasHeightForWidth())
        self.midpoint_label.setSizePolicy(sizePolicy)

        self.horizontalLayout_4.addWidget(self.midpoint_label)

        self.midpoint_value_label = QLabel(self.verticalLayoutWidget_2)
        self.midpoint_value_label.setObjectName(u"midpoint_value_label")

        self.horizontalLayout_4.addWidget(self.midpoint_value_label)


        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.label_23 = QLabel(self.frame_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 40, 67, 17))
        self.verticalLayoutWidget = QWidget(self.frame_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(100, 30, 111, 171))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.lat1 = QLineEdit(self.verticalLayoutWidget)
        self.lat1.setObjectName(u"lat1")

        self.verticalLayout.addWidget(self.lat1)

        self.lon1 = QLineEdit(self.verticalLayoutWidget)
        self.lon1.setObjectName(u"lon1")

        self.verticalLayout.addWidget(self.lon1)

        self.lat2 = QLineEdit(self.verticalLayoutWidget)
        self.lat2.setObjectName(u"lat2")

        self.verticalLayout.addWidget(self.lat2)

        self.lon2 = QLineEdit(self.verticalLayoutWidget)
        self.lon2.setObjectName(u"lon2")

        self.verticalLayout.addWidget(self.lon2)

        self.calculate_button = QPushButton(self.verticalLayoutWidget)
        self.calculate_button.setObjectName(u"calculate_button")

        self.verticalLayout.addWidget(self.calculate_button)

        self.label_24 = QLabel(self.frame_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 110, 67, 17))
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(30, 320, 641, 271))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_4 = QWidget(self.frame_3)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(260, 30, 381, 131))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.destination_point_label = QLabel(self.verticalLayoutWidget_4)
        self.destination_point_label.setObjectName(u"destination_point_label")

        self.horizontalLayout_5.addWidget(self.destination_point_label)

        self.destination_point_value_label = QLabel(self.verticalLayoutWidget_4)
        self.destination_point_value_label.setObjectName(u"destination_point_value_label")

        self.horizontalLayout_5.addWidget(self.destination_point_value_label)


        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.final_bearing_label_2 = QLabel(self.verticalLayoutWidget_4)
        self.final_bearing_label_2.setObjectName(u"final_bearing_label_2")

        self.horizontalLayout_3.addWidget(self.final_bearing_label_2)

        self.final_bearing_value_label = QLabel(self.verticalLayoutWidget_4)
        self.final_bearing_value_label.setObjectName(u"final_bearing_value_label")

        self.horizontalLayout_3.addWidget(self.final_bearing_value_label)


        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.verticalLayoutWidget_3 = QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(100, 20, 111, 211))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.start_lat_lineedit = QLineEdit(self.verticalLayoutWidget_3)
        self.start_lat_lineedit.setObjectName(u"start_lat_lineedit")

        self.verticalLayout_4.addWidget(self.start_lat_lineedit)

        self.start_longitude_lineedit = QLineEdit(self.verticalLayoutWidget_3)
        self.start_longitude_lineedit.setObjectName(u"start_longitude_lineedit")

        self.verticalLayout_4.addWidget(self.start_longitude_lineedit)

        self.bearing_lineEdit = QLineEdit(self.verticalLayoutWidget_3)
        self.bearing_lineEdit.setObjectName(u"bearing_lineEdit")

        self.verticalLayout_4.addWidget(self.bearing_lineEdit)

        self.distance_lineEdit = QLineEdit(self.verticalLayoutWidget_3)
        self.distance_lineEdit.setObjectName(u"distance_lineEdit")

        self.verticalLayout_4.addWidget(self.distance_lineEdit)

        self.calculate_dest_bearing_button = QPushButton(self.verticalLayoutWidget_3)
        self.calculate_dest_bearing_button.setObjectName(u"calculate_dest_bearing_button")

        self.verticalLayout_4.addWidget(self.calculate_dest_bearing_button)

        self.label_25 = QLabel(self.frame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 30, 67, 17))
        self.label_28 = QLabel(self.frame_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 80, 71, 17))
        self.label_27 = QLabel(self.frame_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 120, 67, 17))
        self.label_26 = QLabel(self.frame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 160, 67, 17))
        self.label_42 = QLabel(self.frame_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(220, 160, 67, 17))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayoutWidget_6 = QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(10, 30, 101, 80))
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.verticalLayoutWidget_6)
        self.label_6.setObjectName(u"label_6")

        self.verticalLayout_7.addWidget(self.label_6)

        self.label_7 = QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_7.addWidget(self.label_7)

        self.line_2 = QFrame(self.tab_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(40, 290, 581, 31))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.calculate_button_tab2 = QPushButton(self.tab_2)
        self.calculate_button_tab2.setObjectName(u"calculate_button_tab2")
        self.calculate_button_tab2.setGeometry(QRect(20, 260, 89, 25))
        self.verticalLayoutWidget_8 = QWidget(self.tab_2)
        self.verticalLayoutWidget_8.setObjectName(u"verticalLayoutWidget_8")
        self.verticalLayoutWidget_8.setGeometry(QRect(10, 130, 101, 80))
        self.verticalLayout_9 = QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.verticalLayoutWidget_8)
        self.label_17.setObjectName(u"label_17")

        self.verticalLayout_9.addWidget(self.label_17)

        self.label_18 = QLabel(self.verticalLayoutWidget_8)
        self.label_18.setObjectName(u"label_18")

        self.verticalLayout_9.addWidget(self.label_18)

        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(120, 20, 67, 17))
        self.label_14 = QLabel(self.tab_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(190, 20, 41, 17))
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(240, 20, 67, 17))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 340, 81, 17))
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 410, 81, 17))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 450, 67, 17))
        self.frame = QFrame(self.tab_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(120, 330, 271, 71))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.startpoint_lat_deg_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_deg_lineedit_tab2.setObjectName(u"startpoint_lat_deg_lineedit_tab2")
        self.startpoint_lat_deg_lineedit_tab2.setGeometry(QRect(10, 10, 71, 21))
        self.startpoint_lat_min_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_min_lineedit_tab2.setObjectName(u"startpoint_lat_min_lineedit_tab2")
        self.startpoint_lat_min_lineedit_tab2.setGeometry(QRect(110, 10, 51, 21))
        self.startpoint_lat_sec_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_sec_lineedit_tab2.setObjectName(u"startpoint_lat_sec_lineedit_tab2")
        self.startpoint_lat_sec_lineedit_tab2.setGeometry(QRect(180, 10, 61, 21))
        self.startpoint_lon_min_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_min_lineedit_tab2.setObjectName(u"startpoint_lon_min_lineedit_tab2")
        self.startpoint_lon_min_lineedit_tab2.setGeometry(QRect(110, 40, 51, 21))
        self.startpoint_lon_deg_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_deg_lineedit_tab2.setObjectName(u"startpoint_lon_deg_lineedit_tab2")
        self.startpoint_lon_deg_lineedit_tab2.setGeometry(QRect(10, 40, 71, 21))
        self.startpoint_lon_sec_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_sec_lineedit_tab2.setObjectName(u"startpoint_lon_sec_lineedit_tab2")
        self.startpoint_lon_sec_lineedit_tab2.setGeometry(QRect(180, 40, 61, 21))
        self.label_46 = QLabel(self.frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(90, 10, 16, 16))
        self.label_47 = QLabel(self.frame)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(90, 40, 16, 16))
        self.label_49 = QLabel(self.frame)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(170, 10, 16, 17))
        self.label_50 = QLabel(self.frame)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(170, 40, 16, 17))
        self.label_52 = QLabel(self.frame)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(250, 10, 16, 17))
        self.label_53 = QLabel(self.frame)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(250, 40, 16, 17))
        self.bearing_deg_lineedit_tab2 = QLineEdit(self.tab_2)
        self.bearing_deg_lineedit_tab2.setObjectName(u"bearing_deg_lineedit_tab2")
        self.bearing_deg_lineedit_tab2.setGeometry(QRect(130, 410, 71, 25))
        self.distance_lineedit_tab2 = QLineEdit(self.tab_2)
        self.distance_lineedit_tab2.setObjectName(u"distance_lineedit_tab2")
        self.distance_lineedit_tab2.setGeometry(QRect(120, 450, 113, 25))
        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(540, 330, 121, 17))
        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(540, 360, 101, 17))
        self.destination_label_value_tab2 = QLabel(self.tab_2)
        self.destination_label_value_tab2.setObjectName(u"destination_label_value_tab2")
        self.destination_label_value_tab2.setGeometry(QRect(690, 330, 331, 17))
        self.final_bearing_value_label_lab2 = QLabel(self.tab_2)
        self.final_bearing_value_label_lab2.setObjectName(u"final_bearing_value_label_lab2")
        self.final_bearing_value_label_lab2.setGeometry(QRect(690, 360, 181, 17))
        self.calculate_button_destination_point_tab2 = QPushButton(self.tab_2)
        self.calculate_button_destination_point_tab2.setObjectName(u"calculate_button_destination_point_tab2")
        self.calculate_button_destination_point_tab2.setGeometry(QRect(20, 490, 89, 25))
        self.bearing_min_lineedit_tab2 = QLineEdit(self.tab_2)
        self.bearing_min_lineedit_tab2.setObjectName(u"bearing_min_lineedit_tab2")
        self.bearing_min_lineedit_tab2.setGeometry(QRect(230, 410, 51, 25))
        self.bearing_sec_lineedit_tab2 = QLineEdit(self.tab_2)
        self.bearing_sec_lineedit_tab2.setObjectName(u"bearing_sec_lineedit_tab2")
        self.bearing_sec_lineedit_tab2.setGeometry(QRect(310, 410, 51, 25))
        self.point1_lat_pole = QComboBox(self.tab_2)
        self.point1_lat_pole.setObjectName(u"point1_lat_pole")
        self.point1_lat_pole.setGeometry(QRect(390, 50, 41, 25))
        self.point1_lon_dir = QComboBox(self.tab_2)
        self.point1_lon_dir.setObjectName(u"point1_lon_dir")
        self.point1_lon_dir.setGeometry(QRect(390, 90, 41, 25))
        self.point2_lat_pole = QComboBox(self.tab_2)
        self.point2_lat_pole.setObjectName(u"point2_lat_pole")
        self.point2_lat_pole.setGeometry(QRect(390, 130, 41, 25))
        self.point2_lon_dir = QComboBox(self.tab_2)
        self.point2_lon_dir.setObjectName(u"point2_lon_dir")
        self.point2_lon_dir.setGeometry(QRect(390, 170, 41, 25))
        self.start_point_lat_combo = QComboBox(self.tab_2)
        self.start_point_lat_combo.setObjectName(u"start_point_lat_combo")
        self.start_point_lat_combo.setGeometry(QRect(400, 330, 51, 25))
        self.start_point_lon_combo = QComboBox(self.tab_2)
        self.start_point_lon_combo.setObjectName(u"start_point_lon_combo")
        self.start_point_lon_combo.setGeometry(QRect(400, 360, 51, 25))
        self.label_29 = QLabel(self.tab_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(110, 310, 51, 17))
        self.label_30 = QLabel(self.tab_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(170, 310, 41, 17))
        self.label_31 = QLabel(self.tab_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(210, 310, 67, 17))
        self.frame_4 = QFrame(self.tab_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(120, 40, 261, 81))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.lat1_deg_lineedit = QLineEdit(self.frame_4)
        self.lat1_deg_lineedit.setObjectName(u"lat1_deg_lineedit")
        self.lat1_deg_lineedit.setGeometry(QRect(10, 10, 61, 25))
        self.lat1_min_lineedit = QLineEdit(self.frame_4)
        self.lat1_min_lineedit.setObjectName(u"lat1_min_lineedit")
        self.lat1_min_lineedit.setGeometry(QRect(100, 10, 51, 25))
        self.lat1_sec_lineedit = QLineEdit(self.frame_4)
        self.lat1_sec_lineedit.setObjectName(u"lat1_sec_lineedit")
        self.lat1_sec_lineedit.setGeometry(QRect(170, 10, 61, 25))
        self.lon1_deg_lineedit = QLineEdit(self.frame_4)
        self.lon1_deg_lineedit.setObjectName(u"lon1_deg_lineedit")
        self.lon1_deg_lineedit.setGeometry(QRect(10, 40, 61, 25))
        self.lon1_min_lineedit = QLineEdit(self.frame_4)
        self.lon1_min_lineedit.setObjectName(u"lon1_min_lineedit")
        self.lon1_min_lineedit.setGeometry(QRect(100, 40, 51, 25))
        self.lon1_sec_lineedit = QLineEdit(self.frame_4)
        self.lon1_sec_lineedit.setObjectName(u"lon1_sec_lineedit")
        self.lon1_sec_lineedit.setGeometry(QRect(170, 40, 61, 25))
        self.label_33 = QLabel(self.frame_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(80, 10, 16, 16))
        self.label_32 = QLabel(self.frame_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(80, 40, 16, 17))
        self.label_35 = QLabel(self.frame_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(160, 10, 16, 17))
        self.label_34 = QLabel(self.frame_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(160, 40, 16, 17))
        self.label_36 = QLabel(self.frame_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(240, 20, 20, 20))
        self.label_37 = QLabel(self.frame_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(240, 50, 16, 17))
        self.frame_5 = QFrame(self.tab_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(120, 130, 261, 81))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.lat2_deg_lineedit = QLineEdit(self.frame_5)
        self.lat2_deg_lineedit.setObjectName(u"lat2_deg_lineedit")
        self.lat2_deg_lineedit.setGeometry(QRect(10, 10, 61, 25))
        self.lat2_min_lineedit = QLineEdit(self.frame_5)
        self.lat2_min_lineedit.setObjectName(u"lat2_min_lineedit")
        self.lat2_min_lineedit.setGeometry(QRect(100, 10, 51, 25))
        self.lat2_sec_lineedit = QLineEdit(self.frame_5)
        self.lat2_sec_lineedit.setObjectName(u"lat2_sec_lineedit")
        self.lat2_sec_lineedit.setGeometry(QRect(170, 10, 61, 25))
        self.lon2_deg_lineedit = QLineEdit(self.frame_5)
        self.lon2_deg_lineedit.setObjectName(u"lon2_deg_lineedit")
        self.lon2_deg_lineedit.setGeometry(QRect(10, 50, 61, 25))
        self.lon2_min_lineedit = QLineEdit(self.frame_5)
        self.lon2_min_lineedit.setObjectName(u"lon2_min_lineedit")
        self.lon2_min_lineedit.setGeometry(QRect(100, 50, 51, 25))
        self.lon2_sec_lineedit = QLineEdit(self.frame_5)
        self.lon2_sec_lineedit.setObjectName(u"lon2_sec_lineedit")
        self.lon2_sec_lineedit.setGeometry(QRect(170, 50, 61, 25))
        self.label_38 = QLabel(self.frame_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(80, 10, 16, 16))
        self.label_39 = QLabel(self.frame_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(80, 50, 16, 16))
        self.label_40 = QLabel(self.frame_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(160, 10, 16, 17))
        self.label_41 = QLabel(self.frame_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(160, 50, 16, 17))
        self.label_43 = QLabel(self.frame_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 10, 16, 17))
        self.label_44 = QLabel(self.frame_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(240, 50, 16, 17))
        self.label_45 = QLabel(self.tab_2)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(240, 450, 31, 17))
        self.frame_6 = QFrame(self.tab_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(540, 40, 321, 181))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.frame_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 20, 31, 16))
        self.distance_value_label = QLabel(self.frame_6)
        self.distance_value_label.setObjectName(u"distance_value_label")
        self.distance_value_label.setGeometry(QRect(130, 20, 121, 21))
        self.label_8 = QLabel(self.frame_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 20, 67, 17))
        self.label_9 = QLabel(self.frame_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 60, 71, 31))
        self.label_10 = QLabel(self.frame_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 100, 91, 21))
        self.label_11 = QLabel(self.frame_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 140, 67, 17))
        self.bearing_value_label = QLabel(self.frame_6)
        self.bearing_value_label.setObjectName(u"bearing_value_label")
        self.bearing_value_label.setGeometry(QRect(120, 60, 121, 17))
        self.final_bearing_value_tab2_label = QLabel(self.frame_6)
        self.final_bearing_value_tab2_label.setObjectName(u"final_bearing_value_tab2_label")
        self.final_bearing_value_tab2_label.setGeometry(QRect(130, 100, 131, 17))
        self.midpoint_value_label_tab2 = QLabel(self.frame_6)
        self.midpoint_value_label_tab2.setObjectName(u"midpoint_value_label_tab2")
        self.midpoint_value_label_tab2.setGeometry(QRect(130, 140, 611, 20))
        self.label_48 = QLabel(self.tab_2)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(210, 410, 16, 16))
        self.label_51 = QLabel(self.tab_2)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(290, 410, 16, 17))
        self.label_54 = QLabel(self.tab_2)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(370, 410, 16, 17))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.frame_7 = QFrame(self.tab_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(30, 50, 861, 171))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_55 = QLabel(self.frame_7)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(30, 30, 67, 17))
        self.label_56 = QLabel(self.frame_7)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(30, 90, 67, 17))
        self.lat1_dd_tab3 = QLineEdit(self.frame_7)
        self.lat1_dd_tab3.setObjectName(u"lat1_dd_tab3")
        self.lat1_dd_tab3.setGeometry(QRect(110, 30, 71, 25))
        self.lat2_dd_tab3 = QLineEdit(self.frame_7)
        self.lat2_dd_tab3.setObjectName(u"lat2_dd_tab3")
        self.lat2_dd_tab3.setGeometry(QRect(110, 80, 71, 25))
        self.lon1_dd_tab3 = QLineEdit(self.frame_7)
        self.lon1_dd_tab3.setObjectName(u"lon1_dd_tab3")
        self.lon1_dd_tab3.setGeometry(QRect(190, 30, 71, 25))
        self.lon2_dd_tab3 = QLineEdit(self.frame_7)
        self.lon2_dd_tab3.setObjectName(u"lon2_dd_tab3")
        self.lon2_dd_tab3.setGeometry(QRect(190, 80, 71, 25))
        self.label_57 = QLabel(self.frame_7)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(280, 30, 81, 17))
        self.label_58 = QLabel(self.frame_7)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(280, 80, 81, 17))
        self.bearing1_dd_tab3 = QLineEdit(self.frame_7)
        self.bearing1_dd_tab3.setObjectName(u"bearing1_dd_tab3")
        self.bearing1_dd_tab3.setGeometry(QRect(370, 30, 71, 25))
        self.bearing2_dd_tab3 = QLineEdit(self.frame_7)
        self.bearing2_dd_tab3.setObjectName(u"bearing2_dd_tab3")
        self.bearing2_dd_tab3.setGeometry(QRect(370, 70, 71, 25))
        self.intersection_point_value_label = QLabel(self.frame_7)
        self.intersection_point_value_label.setObjectName(u"intersection_point_value_label")
        self.intersection_point_value_label.setGeometry(QRect(470, 70, 361, 17))
        self.calculate_inter_point_button = QPushButton(self.frame_7)
        self.calculate_inter_point_button.setObjectName(u"calculate_inter_point_button")
        self.calculate_inter_point_button.setGeometry(QRect(30, 130, 89, 25))
        self.label_60 = QLabel(self.frame_7)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(190, 10, 81, 17))
        self.label_59 = QLabel(self.frame_7)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(110, 10, 67, 17))
        self.label_61 = QLabel(self.frame_7)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(470, 30, 201, 17))
        self.label_62 = QLabel(self.tab_3)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(150, 20, 211, 17))
        self.line_3 = QFrame(self.tab_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(70, 260, 791, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_63 = QLabel(self.tab_3)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(140, 290, 111, 17))
        self.frame_8 = QFrame(self.tab_3)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(20, 360, 861, 231))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_64 = QLabel(self.frame_8)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 40, 51, 17))
        self.label_65 = QLabel(self.frame_8)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 110, 51, 17))
        self.lat1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_deg_dms_tab3.setObjectName(u"lat1_deg_dms_tab3")
        self.lat1_deg_dms_tab3.setGeometry(QRect(110, 40, 61, 25))
        self.lat1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_min_dms_tab3.setObjectName(u"lat1_min_dms_tab3")
        self.lat1_min_dms_tab3.setGeometry(QRect(180, 40, 61, 25))
        self.lat1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_sec_dms_tab3.setObjectName(u"lat1_sec_dms_tab3")
        self.lat1_sec_dms_tab3.setGeometry(QRect(250, 40, 61, 25))
        self.point1_pole_tab3 = QComboBox(self.frame_8)
        self.point1_pole_tab3.setObjectName(u"point1_pole_tab3")
        self.point1_pole_tab3.setGeometry(QRect(320, 40, 51, 25))
        self.bearing1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_deg_dms_tab3.setObjectName(u"bearing1_deg_dms_tab3")
        self.bearing1_deg_dms_tab3.setGeometry(QRect(450, 40, 41, 25))
        self.bearing1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_min_dms_tab3.setObjectName(u"bearing1_min_dms_tab3")
        self.bearing1_min_dms_tab3.setGeometry(QRect(500, 40, 41, 25))
        self.bearing1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_sec_dms_tab3.setObjectName(u"bearing1_sec_dms_tab3")
        self.bearing1_sec_dms_tab3.setGeometry(QRect(550, 40, 41, 25))
        self.lat2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_deg_dms_tab3.setObjectName(u"lat2_deg_dms_tab3")
        self.lat2_deg_dms_tab3.setGeometry(QRect(110, 100, 61, 25))
        self.lat2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_min_dms_tab3.setObjectName(u"lat2_min_dms_tab3")
        self.lat2_min_dms_tab3.setGeometry(QRect(180, 100, 61, 25))
        self.lat2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_sec_dms_tab3.setObjectName(u"lat2_sec_dms_tab3")
        self.lat2_sec_dms_tab3.setGeometry(QRect(250, 100, 61, 25))
        self.point2_pole_tab3 = QComboBox(self.frame_8)
        self.point2_pole_tab3.setObjectName(u"point2_pole_tab3")
        self.point2_pole_tab3.setGeometry(QRect(320, 100, 51, 25))
        self.bearing2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_deg_dms_tab3.setObjectName(u"bearing2_deg_dms_tab3")
        self.bearing2_deg_dms_tab3.setGeometry(QRect(450, 110, 41, 25))
        self.bearing2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_min_dms_tab3.setObjectName(u"bearing2_min_dms_tab3")
        self.bearing2_min_dms_tab3.setGeometry(QRect(500, 110, 41, 25))
        self.bearing2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_sec_dms_tab3.setObjectName(u"bearing2_sec_dms_tab3")
        self.bearing2_sec_dms_tab3.setGeometry(QRect(550, 110, 41, 25))
        self.label_66 = QLabel(self.frame_8)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(110, 20, 67, 17))
        self.label_67 = QLabel(self.frame_8)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(180, 20, 67, 17))
        self.label_68 = QLabel(self.frame_8)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(250, 20, 67, 17))
        self.label_69 = QLabel(self.frame_8)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(450, 20, 51, 17))
        self.label_70 = QLabel(self.frame_8)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(510, 20, 41, 17))
        self.label_71 = QLabel(self.frame_8)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(550, 20, 41, 17))
        self.calculate_intersection_dms_button = QPushButton(self.frame_8)
        self.calculate_intersection_dms_button.setObjectName(u"calculate_intersection_dms_button")
        self.calculate_intersection_dms_button.setGeometry(QRect(40, 180, 89, 25))
        self.label_72 = QLabel(self.frame_8)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(160, 180, 131, 17))
        self.intersection_value_dms_label = QLabel(self.frame_8)
        self.intersection_value_dms_label.setObjectName(u"intersection_value_dms_label")
        self.intersection_value_dms_label.setGeometry(QRect(340, 180, 351, 17))
        self.lon1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_deg_dms_tab3.setObjectName(u"lon1_deg_dms_tab3")
        self.lon1_deg_dms_tab3.setGeometry(QRect(110, 70, 61, 25))
        self.lon1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_min_dms_tab3.setObjectName(u"lon1_min_dms_tab3")
        self.lon1_min_dms_tab3.setGeometry(QRect(180, 70, 61, 25))
        self.lon1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_sec_dms_tab3.setObjectName(u"lon1_sec_dms_tab3")
        self.lon1_sec_dms_tab3.setGeometry(QRect(250, 70, 61, 25))
        self.lon2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_deg_dms_tab3.setObjectName(u"lon2_deg_dms_tab3")
        self.lon2_deg_dms_tab3.setGeometry(QRect(110, 130, 61, 25))
        self.lon2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_min_dms_tab3.setObjectName(u"lon2_min_dms_tab3")
        self.lon2_min_dms_tab3.setGeometry(QRect(180, 130, 61, 25))
        self.lon2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_sec_dms_tab3.setObjectName(u"lon2_sec_dms_tab3")
        self.lon2_sec_dms_tab3.setGeometry(QRect(250, 130, 61, 25))
        self.point1_direction_tab3 = QComboBox(self.frame_8)
        self.point1_direction_tab3.setObjectName(u"point1_direction_tab3")
        self.point1_direction_tab3.setGeometry(QRect(320, 70, 51, 25))
        self.point2_direction_tab3 = QComboBox(self.frame_8)
        self.point2_direction_tab3.setObjectName(u"point2_direction_tab3")
        self.point2_direction_tab3.setGeometry(QRect(320, 130, 51, 25))
        self.label_73 = QLabel(self.frame_8)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(80, 40, 31, 17))
        self.label_84 = QLabel(self.frame_8)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(80, 70, 31, 17))
        self.label_85 = QLabel(self.frame_8)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(80, 130, 31, 17))
        self.label_86 = QLabel(self.frame_8)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(80, 110, 31, 17))
        self.label_87 = QLabel(self.frame_8)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(380, 40, 67, 17))
        self.label_88 = QLabel(self.frame_8)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(380, 110, 67, 17))
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1173, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Azimuth", None))
        self.label_value_azamith.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.final_bearing_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.midpoint_label.setText(QCoreApplication.translate("MainWindow", u"Midpoint ", None))
        self.midpoint_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Point1:", None))
        self.lat1.setText("")
        self.lat1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"latitude_1", None))
        self.lon1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"longitude_1", None))
        self.lat2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"latitude_2", None))
        self.lon2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"longitude_2", None))
        self.calculate_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Point1:", None))
        self.destination_point_label.setText(QCoreApplication.translate("MainWindow", u"Destination point", None))
        self.destination_point_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.final_bearing_label_2.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.final_bearing_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.start_lat_lineedit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"start latitude", None))
        self.start_longitude_lineedit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"start longitude", None))
        self.bearing_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"bearing", None))
        self.distance_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"distance", None))
        self.calculate_dest_bearing_button.setText(QCoreApplication.translate("MainWindow", u"Caltulate", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Azamith", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"DD Inputs for distance and destination points", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.calculate_button_tab2.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Second", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Start point", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Bearing", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Destination point", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.destination_label_value_tab2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.final_bearing_value_label_lab2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.calculate_button_destination_point_tab2.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Second", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.distance_value_label.setText(QCoreApplication.translate("MainWindow", u"Distance Value", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Bearing", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Mid Point", None))
        self.bearing_value_label.setText(QCoreApplication.translate("MainWindow", u"Bearing Value", None))
        self.final_bearing_value_tab2_label.setText(QCoreApplication.translate("MainWindow", u"Final bearing value", None))
        self.midpoint_value_label_tab2.setText(QCoreApplication.translate("MainWindow", u"Mid Point Value", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"DMS inputs for distance and destination points", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Point 1:", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Point 2:", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Bearing 1:", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Bearing 2:", None))
        self.intersection_point_value_label.setText(QCoreApplication.translate("MainWindow", u"Intersection point value", None))
        self.calculate_inter_point_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Intersection point:", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"DD inputs", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"DMS inputs", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Point1 :", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Point2 :", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.calculate_intersection_dms_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"Intersection point: ", None))
        self.intersection_value_dms_label.setText(QCoreApplication.translate("MainWindow", u"Intersection point value", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"lat", None))
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"lon", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"lon", None))
        self.label_86.setText(QCoreApplication.translate("MainWindow", u"lat", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"Bearing1:", None))
        self.label_88.setText(QCoreApplication.translate("MainWindow", u"Bearing2:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Intersection points", None))
    # retranslateUi

