# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1173, 770)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 931, 661))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 10, 911, 311))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_22 = QFrame(self.frame_2)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setGeometry(QRect(20, 30, 371, 271))
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.label_24 = QLabel(self.frame_22)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 130, 51, 17))
        self.label_78 = QLabel(self.frame_22)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(90, 130, 81, 17))
        self.label_76 = QLabel(self.frame_22)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(90, 80, 81, 17))
        self.label_74 = QLabel(self.frame_22)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(90, 50, 81, 17))
        self.lat1_pole_tab1 = QComboBox(self.frame_22)
        self.lat1_pole_tab1.setObjectName(u"lat1_pole_tab1")
        self.lat1_pole_tab1.setGeometry(QRect(300, 40, 51, 25))
        self.label_77 = QLabel(self.frame_22)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(90, 170, 81, 17))
        self.lat2_pole_tab1 = QComboBox(self.frame_22)
        self.lat2_pole_tab1.setObjectName(u"lat2_pole_tab1")
        self.lat2_pole_tab1.setGeometry(QRect(300, 130, 51, 25))
        self.lon2_direction_tab1 = QComboBox(self.frame_22)
        self.lon2_direction_tab1.setObjectName(u"lon2_direction_tab1")
        self.lon2_direction_tab1.setGeometry(QRect(300, 170, 51, 25))
        self.label_23 = QLabel(self.frame_22)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 50, 51, 17))
        self.verticalLayoutWidget = QWidget(self.frame_22)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(180, 30, 111, 221))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.lat1 = QLineEdit(self.verticalLayoutWidget)
        self.lat1.setObjectName(u"lat1")

        self.verticalLayout.addWidget(self.lat1)

        self.lon1 = QLineEdit(self.verticalLayoutWidget)
        self.lon1.setObjectName(u"lon1")

        self.verticalLayout.addWidget(self.lon1)

        self.lat2 = QLineEdit(self.verticalLayoutWidget)
        self.lat2.setObjectName(u"lat2")

        self.verticalLayout.addWidget(self.lat2)

        self.lon2 = QLineEdit(self.verticalLayoutWidget)
        self.lon2.setObjectName(u"lon2")

        self.verticalLayout.addWidget(self.lon2)

        self.calculate_button = QPushButton(self.verticalLayoutWidget)
        self.calculate_button.setObjectName(u"calculate_button")

        self.verticalLayout.addWidget(self.calculate_button)

        self.lon1_direction_tab1 = QComboBox(self.frame_22)
        self.lon1_direction_tab1.setObjectName(u"lon1_direction_tab1")
        self.lon1_direction_tab1.setGeometry(QRect(300, 80, 51, 25))
        self.frame_9 = QFrame(self.frame_2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(400, 30, 491, 271))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.frame_11 = QFrame(self.frame_9)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(30, 20, 411, 41))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_11)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 71, 21))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label_2 = QLabel(self.frame_11)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 10, 111, 21))
        self.label_3 = QLabel(self.frame_11)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 10, 101, 16))
        self.frame_19 = QFrame(self.frame_9)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setGeometry(QRect(30, 80, 411, 41))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_19)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 10, 61, 16))
        self.label_4.setFont(font)
        self.label_value_azamith = QLabel(self.frame_19)
        self.label_value_azamith.setObjectName(u"label_value_azamith")
        self.label_value_azamith.setGeometry(QRect(140, 10, 251, 21))
        self.frame_20 = QFrame(self.frame_9)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setGeometry(QRect(30, 140, 411, 41))
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.final_bearing_label = QLabel(self.frame_20)
        self.final_bearing_label.setObjectName(u"final_bearing_label")
        self.final_bearing_label.setGeometry(QRect(140, 10, 251, 21))
        self.label_5 = QLabel(self.frame_20)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 10, 91, 21))
        self.label_5.setFont(font)
        self.frame_21 = QFrame(self.frame_9)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setGeometry(QRect(30, 210, 411, 41))
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.midpoint_value_label = QLabel(self.frame_21)
        self.midpoint_value_label.setObjectName(u"midpoint_value_label")
        self.midpoint_value_label.setGeometry(QRect(140, 10, 261, 21))
        self.midpoint_label = QLabel(self.frame_21)
        self.midpoint_label.setObjectName(u"midpoint_label")
        self.midpoint_label.setGeometry(QRect(20, 10, 91, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midpoint_label.sizePolicy().hasHeightForWidth())
        self.midpoint_label.setSizePolicy(sizePolicy)
        self.midpoint_label.setFont(font)
        self.label_72 = QLabel(self.frame_2)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(210, 0, 491, 20))
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(20, 350, 901, 271))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_10 = QFrame(self.frame_3)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(410, 40, 481, 221))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.frame_12 = QFrame(self.frame_10)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(40, 20, 411, 81))
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.destination_point_label = QLabel(self.frame_12)
        self.destination_point_label.setObjectName(u"destination_point_label")
        self.destination_point_label.setGeometry(QRect(10, 30, 131, 21))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setWeight(75)
        self.destination_point_label.setFont(font1)
        self.destination_point_value_label = QLabel(self.frame_12)
        self.destination_point_value_label.setObjectName(u"destination_point_value_label")
        self.destination_point_value_label.setGeometry(QRect(160, 30, 271, 21))
        self.frame_13 = QFrame(self.frame_10)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(40, 120, 411, 81))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.final_bearing_label_2 = QLabel(self.frame_13)
        self.final_bearing_label_2.setObjectName(u"final_bearing_label_2")
        self.final_bearing_label_2.setGeometry(QRect(20, 30, 91, 21))
        self.final_bearing_label_2.setFont(font1)
        self.final_bearing_value_label = QLabel(self.frame_13)
        self.final_bearing_value_label.setObjectName(u"final_bearing_value_label")
        self.final_bearing_value_label.setGeometry(QRect(160, 30, 121, 21))
        self.frame_17 = QFrame(self.frame_3)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(10, 30, 341, 231))
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.label_27 = QLabel(self.frame_17)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 110, 67, 17))
        self.start_lat_pole_tab1 = QComboBox(self.frame_17)
        self.start_lat_pole_tab1.setObjectName(u"start_lat_pole_tab1")
        self.start_lat_pole_tab1.setGeometry(QRect(220, 50, 51, 25))
        self.label_51 = QLabel(self.frame_17)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(220, 120, 67, 17))
        self.label_25 = QLabel(self.frame_17)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 50, 67, 17))
        self.label_26 = QLabel(self.frame_17)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(30, 150, 67, 17))
        self.start_lon_direction_tab1 = QComboBox(self.frame_17)
        self.start_lon_direction_tab1.setObjectName(u"start_lon_direction_tab1")
        self.start_lon_direction_tab1.setGeometry(QRect(220, 80, 51, 25))
        self.label_28 = QLabel(self.frame_17)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(30, 80, 71, 17))
        self.label_42 = QLabel(self.frame_17)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(220, 140, 67, 17))
        self.start_lat_lineedit = QLineEdit(self.frame_17)
        self.start_lat_lineedit.setObjectName(u"start_lat_lineedit")
        self.start_lat_lineedit.setGeometry(QRect(100, 50, 111, 25))
        self.start_longitude_lineedit = QLineEdit(self.frame_17)
        self.start_longitude_lineedit.setObjectName(u"start_longitude_lineedit")
        self.start_longitude_lineedit.setGeometry(QRect(100, 80, 111, 25))
        self.bearing_lineEdit = QLineEdit(self.frame_17)
        self.bearing_lineEdit.setObjectName(u"bearing_lineEdit")
        self.bearing_lineEdit.setGeometry(QRect(100, 110, 111, 25))
        self.distance_lineEdit = QLineEdit(self.frame_17)
        self.distance_lineEdit.setObjectName(u"distance_lineEdit")
        self.distance_lineEdit.setGeometry(QRect(100, 140, 111, 25))
        self.calculate_dest_bearing_button = QPushButton(self.frame_17)
        self.calculate_dest_bearing_button.setObjectName(u"calculate_dest_bearing_button")
        self.calculate_dest_bearing_button.setGeometry(QRect(20, 190, 91, 25))
        self.label_91 = QLabel(self.frame_17)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(30, 30, 81, 17))
        font2 = QFont()
        font2.setUnderline(True)
        self.label_91.setFont(font2)
        self.label_80 = QLabel(self.frame_3)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(130, 0, 741, 20))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.frame_6 = QFrame(self.tab_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(530, 40, 371, 231))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_26 = QFrame(self.frame_6)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setGeometry(QRect(10, 10, 351, 41))
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.distance_value_label = QLabel(self.frame_26)
        self.distance_value_label.setObjectName(u"distance_value_label")
        self.distance_value_label.setGeometry(QRect(120, 10, 121, 21))
        self.label_13 = QLabel(self.frame_26)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 10, 31, 16))
        self.label_8 = QLabel(self.frame_26)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 67, 17))
        self.label_8.setFont(font)
        self.frame_27 = QFrame(self.frame_6)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setGeometry(QRect(10, 60, 351, 41))
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.bearing_value_label = QLabel(self.frame_27)
        self.bearing_value_label.setObjectName(u"bearing_value_label")
        self.bearing_value_label.setGeometry(QRect(120, 10, 121, 21))
        self.label_9 = QLabel(self.frame_27)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 71, 21))
        self.label_9.setFont(font)
        self.frame_28 = QFrame(self.frame_6)
        self.frame_28.setObjectName(u"frame_28")
        self.frame_28.setGeometry(QRect(10, 110, 351, 41))
        self.frame_28.setFrameShape(QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QFrame.Raised)
        self.final_bearing_value_tab2_label = QLabel(self.frame_28)
        self.final_bearing_value_tab2_label.setObjectName(u"final_bearing_value_tab2_label")
        self.final_bearing_value_tab2_label.setGeometry(QRect(120, 10, 131, 17))
        self.label_10 = QLabel(self.frame_28)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 10, 101, 21))
        self.label_10.setFont(font)
        self.frame_29 = QFrame(self.frame_6)
        self.frame_29.setObjectName(u"frame_29")
        self.frame_29.setGeometry(QRect(10, 170, 351, 41))
        self.frame_29.setFrameShape(QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QFrame.Raised)
        self.midpoint_value_label_tab2 = QLabel(self.frame_29)
        self.midpoint_value_label_tab2.setObjectName(u"midpoint_value_label_tab2")
        self.midpoint_value_label_tab2.setGeometry(QRect(120, 10, 611, 20))
        self.label_11 = QLabel(self.frame_29)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 67, 17))
        self.label_11.setFont(font)
        self.frame_23 = QFrame(self.tab_2)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setGeometry(QRect(10, 40, 481, 291))
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.label_17 = QLabel(self.frame_23)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 170, 61, 20))
        self.label_18 = QLabel(self.frame_23)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 200, 71, 21))
        self.label_6 = QLabel(self.frame_23)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 40, 99, 36))
        self.label_7 = QLabel(self.frame_23)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 60, 99, 36))
        self.point2_lat_pole = QComboBox(self.frame_23)
        self.point2_lat_pole.setObjectName(u"point2_lat_pole")
        self.point2_lat_pole.setGeometry(QRect(380, 150, 41, 25))
        self.point1_lat_pole = QComboBox(self.frame_23)
        self.point1_lat_pole.setObjectName(u"point1_lat_pole")
        self.point1_lat_pole.setGeometry(QRect(380, 40, 41, 25))
        self.point2_lon_dir = QComboBox(self.frame_23)
        self.point2_lon_dir.setObjectName(u"point2_lon_dir")
        self.point2_lon_dir.setGeometry(QRect(380, 190, 41, 25))
        self.point1_lon_dir = QComboBox(self.frame_23)
        self.point1_lon_dir.setObjectName(u"point1_lon_dir")
        self.point1_lon_dir.setGeometry(QRect(380, 80, 41, 25))
        self.frame_4 = QFrame(self.frame_23)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(110, 30, 261, 81))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.lat1_deg_lineedit = QLineEdit(self.frame_4)
        self.lat1_deg_lineedit.setObjectName(u"lat1_deg_lineedit")
        self.lat1_deg_lineedit.setGeometry(QRect(10, 10, 61, 25))
        self.lat1_min_lineedit = QLineEdit(self.frame_4)
        self.lat1_min_lineedit.setObjectName(u"lat1_min_lineedit")
        self.lat1_min_lineedit.setGeometry(QRect(100, 10, 51, 25))
        self.lat1_sec_lineedit = QLineEdit(self.frame_4)
        self.lat1_sec_lineedit.setObjectName(u"lat1_sec_lineedit")
        self.lat1_sec_lineedit.setGeometry(QRect(170, 10, 61, 25))
        self.lon1_deg_lineedit = QLineEdit(self.frame_4)
        self.lon1_deg_lineedit.setObjectName(u"lon1_deg_lineedit")
        self.lon1_deg_lineedit.setGeometry(QRect(10, 40, 61, 25))
        self.lon1_min_lineedit = QLineEdit(self.frame_4)
        self.lon1_min_lineedit.setObjectName(u"lon1_min_lineedit")
        self.lon1_min_lineedit.setGeometry(QRect(100, 40, 51, 25))
        self.lon1_sec_lineedit = QLineEdit(self.frame_4)
        self.lon1_sec_lineedit.setObjectName(u"lon1_sec_lineedit")
        self.lon1_sec_lineedit.setGeometry(QRect(170, 40, 61, 25))
        self.label_33 = QLabel(self.frame_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(80, 10, 16, 16))
        self.label_32 = QLabel(self.frame_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(80, 40, 16, 16))
        self.label_35 = QLabel(self.frame_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(160, 10, 16, 17))
        self.label_34 = QLabel(self.frame_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(160, 40, 16, 17))
        self.label_36 = QLabel(self.frame_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(240, 20, 20, 20))
        self.label_37 = QLabel(self.frame_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(240, 50, 16, 17))
        self.frame_5 = QFrame(self.frame_23)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(110, 150, 261, 81))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.lat2_deg_lineedit = QLineEdit(self.frame_5)
        self.lat2_deg_lineedit.setObjectName(u"lat2_deg_lineedit")
        self.lat2_deg_lineedit.setGeometry(QRect(10, 10, 61, 25))
        self.lat2_min_lineedit = QLineEdit(self.frame_5)
        self.lat2_min_lineedit.setObjectName(u"lat2_min_lineedit")
        self.lat2_min_lineedit.setGeometry(QRect(100, 10, 51, 25))
        self.lat2_sec_lineedit = QLineEdit(self.frame_5)
        self.lat2_sec_lineedit.setObjectName(u"lat2_sec_lineedit")
        self.lat2_sec_lineedit.setGeometry(QRect(170, 10, 61, 25))
        self.lon2_deg_lineedit = QLineEdit(self.frame_5)
        self.lon2_deg_lineedit.setObjectName(u"lon2_deg_lineedit")
        self.lon2_deg_lineedit.setGeometry(QRect(10, 50, 61, 25))
        self.lon2_min_lineedit = QLineEdit(self.frame_5)
        self.lon2_min_lineedit.setObjectName(u"lon2_min_lineedit")
        self.lon2_min_lineedit.setGeometry(QRect(100, 50, 51, 25))
        self.lon2_sec_lineedit = QLineEdit(self.frame_5)
        self.lon2_sec_lineedit.setObjectName(u"lon2_sec_lineedit")
        self.lon2_sec_lineedit.setGeometry(QRect(170, 50, 61, 25))
        self.label_38 = QLabel(self.frame_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(80, 10, 16, 16))
        self.label_39 = QLabel(self.frame_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(80, 50, 16, 16))
        self.label_40 = QLabel(self.frame_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(160, 10, 16, 17))
        self.label_41 = QLabel(self.frame_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(160, 50, 16, 17))
        self.label_43 = QLabel(self.frame_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 10, 16, 17))
        self.label_44 = QLabel(self.frame_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(240, 50, 16, 17))
        self.label_12 = QLabel(self.frame_23)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(120, 10, 67, 17))
        self.label_14 = QLabel(self.frame_23)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(220, 10, 41, 17))
        self.label_15 = QLabel(self.frame_23)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(290, 10, 67, 17))
        self.calculate_button_tab2 = QPushButton(self.frame_23)
        self.calculate_button_tab2.setObjectName(u"calculate_button_tab2")
        self.calculate_button_tab2.setGeometry(QRect(30, 250, 89, 25))
        self.label_81 = QLabel(self.frame_23)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(40, 20, 67, 17))
        self.label_81.setFont(font2)
        self.label_82 = QLabel(self.frame_23)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(50, 140, 67, 17))
        self.label_82.setFont(font2)
        self.frame_24 = QFrame(self.tab_2)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setGeometry(QRect(530, 360, 371, 141))
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.frame_30 = QFrame(self.frame_24)
        self.frame_30.setObjectName(u"frame_30")
        self.frame_30.setGeometry(QRect(10, 20, 351, 41))
        self.frame_30.setFrameShape(QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QFrame.Raised)
        self.destination_label_value_tab2 = QLabel(self.frame_30)
        self.destination_label_value_tab2.setObjectName(u"destination_label_value_tab2")
        self.destination_label_value_tab2.setGeometry(QRect(150, 10, 331, 17))
        self.label_21 = QLabel(self.frame_30)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 10, 141, 17))
        self.label_21.setFont(font)
        self.frame_31 = QFrame(self.frame_24)
        self.frame_31.setObjectName(u"frame_31")
        self.frame_31.setGeometry(QRect(10, 80, 351, 41))
        self.frame_31.setFrameShape(QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QFrame.Raised)
        self.final_bearing_value_label_lab2 = QLabel(self.frame_31)
        self.final_bearing_value_label_lab2.setObjectName(u"final_bearing_value_label_lab2")
        self.final_bearing_value_label_lab2.setGeometry(QRect(150, 10, 181, 17))
        self.label_22 = QLabel(self.frame_31)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 10, 101, 17))
        self.label_22.setFont(font)
        self.frame_25 = QFrame(self.tab_2)
        self.frame_25.setObjectName(u"frame_25")
        self.frame_25.setGeometry(QRect(10, 370, 491, 241))
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.start_point_lat_combo = QComboBox(self.frame_25)
        self.start_point_lat_combo.setObjectName(u"start_point_lat_combo")
        self.start_point_lat_combo.setGeometry(QRect(400, 40, 51, 25))
        self.start_point_lon_combo = QComboBox(self.frame_25)
        self.start_point_lon_combo.setObjectName(u"start_point_lon_combo")
        self.start_point_lon_combo.setGeometry(QRect(400, 80, 51, 25))
        self.frame = QFrame(self.frame_25)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(120, 40, 271, 71))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.startpoint_lat_deg_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_deg_lineedit_tab2.setObjectName(u"startpoint_lat_deg_lineedit_tab2")
        self.startpoint_lat_deg_lineedit_tab2.setGeometry(QRect(10, 10, 71, 21))
        self.startpoint_lat_min_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_min_lineedit_tab2.setObjectName(u"startpoint_lat_min_lineedit_tab2")
        self.startpoint_lat_min_lineedit_tab2.setGeometry(QRect(110, 10, 51, 21))
        self.startpoint_lat_sec_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lat_sec_lineedit_tab2.setObjectName(u"startpoint_lat_sec_lineedit_tab2")
        self.startpoint_lat_sec_lineedit_tab2.setGeometry(QRect(180, 10, 61, 21))
        self.startpoint_lon_min_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_min_lineedit_tab2.setObjectName(u"startpoint_lon_min_lineedit_tab2")
        self.startpoint_lon_min_lineedit_tab2.setGeometry(QRect(110, 40, 51, 21))
        self.startpoint_lon_deg_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_deg_lineedit_tab2.setObjectName(u"startpoint_lon_deg_lineedit_tab2")
        self.startpoint_lon_deg_lineedit_tab2.setGeometry(QRect(10, 40, 71, 21))
        self.startpoint_lon_sec_lineedit_tab2 = QLineEdit(self.frame)
        self.startpoint_lon_sec_lineedit_tab2.setObjectName(u"startpoint_lon_sec_lineedit_tab2")
        self.startpoint_lon_sec_lineedit_tab2.setGeometry(QRect(180, 40, 61, 21))
        self.label_46 = QLabel(self.frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(90, 10, 16, 16))
        self.label_47 = QLabel(self.frame)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(90, 40, 16, 16))
        self.label_49 = QLabel(self.frame)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(170, 10, 16, 17))
        self.label_50 = QLabel(self.frame)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(170, 40, 16, 17))
        self.label_52 = QLabel(self.frame)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(250, 10, 16, 17))
        self.label_53 = QLabel(self.frame)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(250, 40, 16, 17))
        self.bearing_deg_lineedit_tab2 = QLineEdit(self.frame_25)
        self.bearing_deg_lineedit_tab2.setObjectName(u"bearing_deg_lineedit_tab2")
        self.bearing_deg_lineedit_tab2.setGeometry(QRect(130, 120, 71, 25))
        self.label_48 = QLabel(self.frame_25)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(210, 130, 16, 16))
        self.distance_lineedit_tab2 = QLineEdit(self.frame_25)
        self.distance_lineedit_tab2.setObjectName(u"distance_lineedit_tab2")
        self.distance_lineedit_tab2.setGeometry(QRect(130, 160, 113, 25))
        self.label_45 = QLabel(self.frame_25)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(250, 160, 41, 31))
        self.calculate_button_destination_point_tab2 = QPushButton(self.frame_25)
        self.calculate_button_destination_point_tab2.setObjectName(u"calculate_button_destination_point_tab2")
        self.calculate_button_destination_point_tab2.setGeometry(QRect(10, 200, 89, 25))
        self.label_20 = QLabel(self.frame_25)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 160, 81, 17))
        self.label_19 = QLabel(self.frame_25)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 120, 81, 17))
        self.label_16 = QLabel(self.frame_25)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 20, 81, 17))
        self.label_16.setFont(font2)
        self.label_31 = QLabel(self.frame_25)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(300, 10, 67, 17))
        self.label_30 = QLabel(self.frame_25)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(240, 10, 41, 17))
        self.label_29 = QLabel(self.frame_25)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(140, 10, 51, 17))
        self.label_92 = QLabel(self.frame_25)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(20, 50, 81, 17))
        self.label_93 = QLabel(self.frame_25)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(20, 80, 81, 17))
        self.label_83 = QLabel(self.tab_2)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(50, 10, 491, 20))
        self.label_89 = QLabel(self.tab_2)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(10, 340, 741, 20))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.frame_7 = QFrame(self.tab_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 40, 891, 261))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.calculate_inter_point_button = QPushButton(self.frame_7)
        self.calculate_inter_point_button.setObjectName(u"calculate_inter_point_button")
        self.calculate_inter_point_button.setGeometry(QRect(20, 200, 89, 25))
        self.frame_14 = QFrame(self.frame_7)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(20, 40, 591, 151))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.lon1_dd_tab3 = QLineEdit(self.frame_14)
        self.lon1_dd_tab3.setObjectName(u"lon1_dd_tab3")
        self.lon1_dd_tab3.setGeometry(QRect(270, 40, 71, 25))
        self.lat1_pole_tab3 = QComboBox(self.frame_14)
        self.lat1_pole_tab3.setObjectName(u"lat1_pole_tab3")
        self.lat1_pole_tab3.setGeometry(QRect(210, 40, 41, 25))
        self.lon1_tab3_dir = QComboBox(self.frame_14)
        self.lon1_tab3_dir.setObjectName(u"lon1_tab3_dir")
        self.lon1_tab3_dir.setGeometry(QRect(350, 40, 41, 25))
        self.lat1_dd_tab3 = QLineEdit(self.frame_14)
        self.lat1_dd_tab3.setObjectName(u"lat1_dd_tab3")
        self.lat1_dd_tab3.setGeometry(QRect(120, 40, 71, 25))
        self.lon2_dir_tab3 = QComboBox(self.frame_14)
        self.lon2_dir_tab3.setObjectName(u"lon2_dir_tab3")
        self.lon2_dir_tab3.setGeometry(QRect(350, 80, 41, 25))
        self.lat2_dd_tab3 = QLineEdit(self.frame_14)
        self.lat2_dd_tab3.setObjectName(u"lat2_dd_tab3")
        self.lat2_dd_tab3.setGeometry(QRect(120, 80, 71, 25))
        self.lat2_pole_tab3 = QComboBox(self.frame_14)
        self.lat2_pole_tab3.setObjectName(u"lat2_pole_tab3")
        self.lat2_pole_tab3.setGeometry(QRect(210, 80, 41, 25))
        self.lon2_dd_tab3 = QLineEdit(self.frame_14)
        self.lon2_dd_tab3.setObjectName(u"lon2_dd_tab3")
        self.lon2_dd_tab3.setGeometry(QRect(270, 80, 71, 25))
        self.bearing2_dd_tab3 = QLineEdit(self.frame_14)
        self.bearing2_dd_tab3.setObjectName(u"bearing2_dd_tab3")
        self.bearing2_dd_tab3.setGeometry(QRect(480, 80, 61, 21))
        self.label_57 = QLabel(self.frame_14)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(400, 40, 81, 17))
        self.bearing1_dd_tab3 = QLineEdit(self.frame_14)
        self.bearing1_dd_tab3.setObjectName(u"bearing1_dd_tab3")
        self.bearing1_dd_tab3.setGeometry(QRect(480, 40, 61, 21))
        self.label_59 = QLabel(self.frame_14)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(120, 20, 67, 17))
        self.label_60 = QLabel(self.frame_14)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(270, 20, 81, 17))
        self.label_55 = QLabel(self.frame_14)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(40, 40, 67, 17))
        self.label_56 = QLabel(self.frame_14)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(40, 80, 67, 17))
        self.label_58 = QLabel(self.frame_14)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(400, 80, 81, 17))
        self.label_54 = QLabel(self.frame_14)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(550, 40, 16, 17))
        self.label_75 = QLabel(self.frame_14)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(550, 80, 16, 17))
        self.frame_15 = QFrame(self.frame_7)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(620, 40, 251, 151))
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.frame_32 = QFrame(self.frame_15)
        self.frame_32.setObjectName(u"frame_32")
        self.frame_32.setGeometry(QRect(10, 10, 221, 41))
        self.frame_32.setFrameShape(QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QFrame.Raised)
        self.label_61 = QLabel(self.frame_32)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 10, 201, 17))
        self.label_61.setFont(font)
        self.frame_33 = QFrame(self.frame_15)
        self.frame_33.setObjectName(u"frame_33")
        self.frame_33.setGeometry(QRect(10, 70, 221, 41))
        self.frame_33.setFrameShape(QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QFrame.Raised)
        self.intersection_point_value_label = QLabel(self.frame_33)
        self.intersection_point_value_label.setObjectName(u"intersection_point_value_label")
        self.intersection_point_value_label.setGeometry(QRect(10, 10, 361, 17))
        self.label_62 = QLabel(self.frame_7)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(220, 20, 211, 17))
        self.frame_16 = QFrame(self.tab_3)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(10, 320, 891, 291))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.frame_8 = QFrame(self.frame_16)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(20, 30, 591, 191))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_64 = QLabel(self.frame_8)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 40, 51, 17))
        self.label_65 = QLabel(self.frame_8)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 110, 51, 17))
        self.lat1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_deg_dms_tab3.setObjectName(u"lat1_deg_dms_tab3")
        self.lat1_deg_dms_tab3.setGeometry(QRect(100, 40, 61, 25))
        self.lat1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_min_dms_tab3.setObjectName(u"lat1_min_dms_tab3")
        self.lat1_min_dms_tab3.setGeometry(QRect(170, 40, 61, 25))
        self.lat1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lat1_sec_dms_tab3.setObjectName(u"lat1_sec_dms_tab3")
        self.lat1_sec_dms_tab3.setGeometry(QRect(240, 40, 61, 25))
        self.point1_pole_tab3 = QComboBox(self.frame_8)
        self.point1_pole_tab3.setObjectName(u"point1_pole_tab3")
        self.point1_pole_tab3.setGeometry(QRect(310, 40, 51, 25))
        self.bearing1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_deg_dms_tab3.setObjectName(u"bearing1_deg_dms_tab3")
        self.bearing1_deg_dms_tab3.setGeometry(QRect(440, 40, 41, 25))
        self.bearing1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_min_dms_tab3.setObjectName(u"bearing1_min_dms_tab3")
        self.bearing1_min_dms_tab3.setGeometry(QRect(490, 40, 41, 25))
        self.bearing1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing1_sec_dms_tab3.setObjectName(u"bearing1_sec_dms_tab3")
        self.bearing1_sec_dms_tab3.setGeometry(QRect(540, 40, 41, 25))
        self.lat2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_deg_dms_tab3.setObjectName(u"lat2_deg_dms_tab3")
        self.lat2_deg_dms_tab3.setGeometry(QRect(100, 100, 61, 25))
        self.lat2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_min_dms_tab3.setObjectName(u"lat2_min_dms_tab3")
        self.lat2_min_dms_tab3.setGeometry(QRect(170, 100, 61, 25))
        self.lat2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lat2_sec_dms_tab3.setObjectName(u"lat2_sec_dms_tab3")
        self.lat2_sec_dms_tab3.setGeometry(QRect(240, 100, 61, 25))
        self.point2_pole_tab3 = QComboBox(self.frame_8)
        self.point2_pole_tab3.setObjectName(u"point2_pole_tab3")
        self.point2_pole_tab3.setGeometry(QRect(310, 100, 51, 25))
        self.bearing2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_deg_dms_tab3.setObjectName(u"bearing2_deg_dms_tab3")
        self.bearing2_deg_dms_tab3.setGeometry(QRect(440, 110, 41, 25))
        self.bearing2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_min_dms_tab3.setObjectName(u"bearing2_min_dms_tab3")
        self.bearing2_min_dms_tab3.setGeometry(QRect(490, 110, 41, 25))
        self.bearing2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.bearing2_sec_dms_tab3.setObjectName(u"bearing2_sec_dms_tab3")
        self.bearing2_sec_dms_tab3.setGeometry(QRect(540, 110, 41, 25))
        self.label_66 = QLabel(self.frame_8)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(100, 20, 67, 17))
        self.label_67 = QLabel(self.frame_8)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(180, 20, 67, 17))
        self.label_68 = QLabel(self.frame_8)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(260, 20, 67, 17))
        self.label_69 = QLabel(self.frame_8)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(440, 20, 51, 17))
        self.label_70 = QLabel(self.frame_8)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(500, 20, 41, 17))
        self.label_71 = QLabel(self.frame_8)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(540, 20, 41, 17))
        self.lon1_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_deg_dms_tab3.setObjectName(u"lon1_deg_dms_tab3")
        self.lon1_deg_dms_tab3.setGeometry(QRect(100, 70, 61, 25))
        self.lon1_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_min_dms_tab3.setObjectName(u"lon1_min_dms_tab3")
        self.lon1_min_dms_tab3.setGeometry(QRect(170, 70, 61, 25))
        self.lon1_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lon1_sec_dms_tab3.setObjectName(u"lon1_sec_dms_tab3")
        self.lon1_sec_dms_tab3.setGeometry(QRect(240, 70, 61, 25))
        self.lon2_deg_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_deg_dms_tab3.setObjectName(u"lon2_deg_dms_tab3")
        self.lon2_deg_dms_tab3.setGeometry(QRect(100, 130, 61, 25))
        self.lon2_min_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_min_dms_tab3.setObjectName(u"lon2_min_dms_tab3")
        self.lon2_min_dms_tab3.setGeometry(QRect(170, 130, 61, 25))
        self.lon2_sec_dms_tab3 = QLineEdit(self.frame_8)
        self.lon2_sec_dms_tab3.setObjectName(u"lon2_sec_dms_tab3")
        self.lon2_sec_dms_tab3.setGeometry(QRect(240, 130, 61, 25))
        self.point1_direction_tab3 = QComboBox(self.frame_8)
        self.point1_direction_tab3.setObjectName(u"point1_direction_tab3")
        self.point1_direction_tab3.setGeometry(QRect(310, 70, 51, 25))
        self.point2_direction_tab3 = QComboBox(self.frame_8)
        self.point2_direction_tab3.setObjectName(u"point2_direction_tab3")
        self.point2_direction_tab3.setGeometry(QRect(310, 130, 51, 25))
        self.label_73 = QLabel(self.frame_8)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(70, 40, 31, 17))
        self.label_84 = QLabel(self.frame_8)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(70, 70, 31, 17))
        self.label_85 = QLabel(self.frame_8)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(70, 130, 31, 17))
        self.label_86 = QLabel(self.frame_8)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(70, 110, 31, 17))
        self.label_87 = QLabel(self.frame_8)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(370, 40, 67, 17))
        self.label_88 = QLabel(self.frame_8)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(370, 110, 67, 17))
        self.label_63 = QLabel(self.frame_16)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(180, 10, 261, 17))
        self.calculate_intersection_dms_button = QPushButton(self.frame_16)
        self.calculate_intersection_dms_button.setObjectName(u"calculate_intersection_dms_button")
        self.calculate_intersection_dms_button.setGeometry(QRect(20, 240, 89, 25))
        self.frame_18 = QFrame(self.frame_16)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setGeometry(QRect(620, 40, 251, 191))
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.frame_34 = QFrame(self.frame_18)
        self.frame_34.setObjectName(u"frame_34")
        self.frame_34.setGeometry(QRect(10, 10, 221, 41))
        self.frame_34.setFrameShape(QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QFrame.Raised)
        self.label_79 = QLabel(self.frame_34)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(20, 10, 131, 17))
        self.label_79.setFont(font)
        self.frame_35 = QFrame(self.frame_18)
        self.frame_35.setObjectName(u"frame_35")
        self.frame_35.setGeometry(QRect(10, 70, 221, 41))
        self.frame_35.setFrameShape(QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QFrame.Raised)
        self.intersection_value_dms_label = QLabel(self.frame_35)
        self.intersection_value_dms_label.setObjectName(u"intersection_value_dms_label")
        self.intersection_value_dms_label.setGeometry(QRect(10, 10, 351, 17))
        self.label_90 = QLabel(self.tab_3)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(250, 10, 521, 17))
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1173, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Point2:", None))
        self.label_78.setText(QCoreApplication.translate("MainWindow", u"Latitude   :", None))
        self.label_76.setText(QCoreApplication.translate("MainWindow", u"Longitude:", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"Latitude   :", None))
        self.label_77.setText(QCoreApplication.translate("MainWindow", u"Longitude:", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Point1:", None))
        self.lat1.setText("")
        self.lat1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"latitude_1", None))
        self.lon1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"longitude_1", None))
        self.lat2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"latitude_2", None))
        self.lon2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"longitude_2", None))
        self.calculate_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Azimuth", None))
        self.label_value_azamith.setText("")
        self.final_bearing_label.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.midpoint_value_label.setText("")
        self.midpoint_label.setText(QCoreApplication.translate("MainWindow", u"Midpoint ", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"Finding Distance, Azimuth, Final Bearing and Midpoint", None))
        self.destination_point_label.setText(QCoreApplication.translate("MainWindow", u"Destination point", None))
        self.destination_point_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.final_bearing_label_2.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.final_bearing_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Azimuth", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.start_lat_lineedit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"start latitude", None))
        self.start_longitude_lineedit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"start longitude", None))
        self.bearing_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"bearing", None))
        self.distance_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"distance", None))
        self.calculate_dest_bearing_button.setText(QCoreApplication.translate("MainWindow", u"Caltulate", None))
        self.label_91.setText(QCoreApplication.translate("MainWindow", u"Start Point", None))
        self.label_80.setText(QCoreApplication.translate("MainWindow", u"Finding Destination point and Final Bearing when Start Point, Azimuth and Distance is given", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Find Distance (input type: Decimal Degree)", None))
        self.distance_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.bearing_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Bearing", None))
        self.final_bearing_value_tab2_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.midpoint_value_label_tab2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Mid Point", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Second", None))
        self.calculate_button_tab2.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_81.setText(QCoreApplication.translate("MainWindow", u"Point 1", None))
        self.label_82.setText(QCoreApplication.translate("MainWindow", u"Point 2", None))
        self.destination_label_value_tab2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Destination point", None))
        self.final_bearing_value_label_lab2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Final bearing", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"''", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"km", None))
        self.calculate_button_destination_point_tab2.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Distance  :", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Bearing    :", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Start point", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Second", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_92.setText(QCoreApplication.translate("MainWindow", u"Latitude   :", None))
        self.label_93.setText(QCoreApplication.translate("MainWindow", u"Longitude:", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"Finding Distance, Azimuth, Final Bearing and Midpoint", None))
        self.label_89.setText(QCoreApplication.translate("MainWindow", u"Finding Destination point and Final Bearing when Start Point, Azimuth and Distance is given", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Find Distance (input type: Deg Min Sec)", None))
        self.calculate_inter_point_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Bearing 1:", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Point 1:", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Point 2:", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Bearing 2:", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Intersection point:", None))
        self.intersection_point_value_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"Decimal degree inputs", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Point1 :", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Point2 :", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Degree", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Min", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"lat", None))
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"lon", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"lon", None))
        self.label_86.setText(QCoreApplication.translate("MainWindow", u"lat", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"Bearing1:", None))
        self.label_88.setText(QCoreApplication.translate("MainWindow", u"Bearing2:", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"Degree Minute Second Inputs", None))
        self.calculate_intersection_dms_button.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_79.setText(QCoreApplication.translate("MainWindow", u"Intersection point: ", None))
        self.intersection_value_dms_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_90.setText(QCoreApplication.translate("MainWindow", u"Finding Intersection points", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Find Intersection points (input type: both)", None))
    # retranslateUi

